### ISSUE TITLE
Update layout data download page

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/bridgedb.github.io#4]
See image: 
![image](https://user-images.githubusercontent.com/26277832/91320149-8128ee80-e7bd-11ea-9da6-a929acb7c124.png)
Green bar on top of page is missing.

**Comment by DeniseSl22** [comment]
Related to https://github.com/bridgedb/data/issues/4

**Comment by egonw** [comment]
![image](https://user-images.githubusercontent.com/26721/236621478-501640cb-6758-4cde-97ee-3f590ada7371.png)
